-- ============================================================
-- DATOS DE CONFIGURACIÓN
-- ============================================================
-- Las tablas "grados-informaticos".filas y ".archivos" ya NO existen.
-- La visibilidad y el listado de material se gestionan directamente
-- moviendo filas de los CSV entre el repositorio privado y el público.
--
-- El contenido real de APUNTES.csv y
-- EJERCICIOS_PRACTICAS_PROYECTOS.csv vive en GitHub.
-- Por defecto todo está en el repositorio privado.
-- ============================================================

-- No hay inserts de filas/archivos en este archivo.
